### ISSUE TITLE
history view only displaying last commit

### ISSUE THREAD

**Issue by balmas** [sosol/sosol#105]
Haven't debugged this yet, but it seems that the history view is now only displaying the last commit.

Will look into it further tomorrow.

**Comment by balmas** [comment]
ah seems intentional: 910199ddf59ce089254b30a2700de2930223cc3d

I think we need a little more navigation support here, maybe allowing the user to request history in configurable sizes -- and allowing show_commit to work by passing the commit hash to the log request so that we can at least navigate backwards through the list.

**Comment by ryanfb** [comment]
There's some commits related to this on the `remove_grit` branch: https://github.com/sosol/sosol/commits/remove_grit (see #81)

I think the Grit version was relatively slow, the version on `remove_grit` seems fast enough for me in development and 20 seemed like a reasonably large first adjustment to see if we ran into problems.

**Comment by balmas** [comment]
Ok, thanks. I will wait for this branch then.

**Comment by ryanfb** [comment]
Note that at least with the Git we're running on papyri.info dev/prodo (1.7.1), the `remove_grit` version which calls `git log -n #{limit} -- #{filename}` the commit limit appears to be applied *before* filename filtering. This seems to make things faster, at least in that version of Git, but files with lots of old history wind up not showing much of it. Not sure when this behavior was changed in Git because as of 2.5.0 on my Mac the filename limit is applied before the commit limit (giving you a more complete file history), while appearing to stay pretty fast even with the `idp.data` repository.

**Comment by ryanfb** [comment]
Should now be fixed with #81 (Remove Grit) merged.
