### ISSUE TITLE
Rescue/present "RuntimeError: Illegal character" in IdentifiersController#updatexml

### ISSUE THREAD

**Issue by ryanfb** [sosol/sosol#231]
Currently wind up with e.g.:
```
#<RuntimeError: Illegal character '&' in raw string "William Furley & Victor Gysembergh, Reading the Liver. Papyrological Texts on Ancient Greek Extispicy = Studien und Texte zu Antike und Christentum. 94."> 
```
From `app/controllers/identifiers_controller.rb:90→ updatexml`

We should rescue this in the controller and flash the error message to the user.

Perhaps should also link to XML escaping guidelines (I believe this should work with `&amp;` instead of `&`)? /cc @jcowey

**Comment by jcowey** [comment]
I got a something went wrong message. Clicked back to where I had been in the editor and changed & to &amp;. I then carried on without any problem (having realised the mistake). The file was committed hours ago:

https://github.com/papyri/idp.data/blob/master/Biblio/96/95416.xml#L24

Flagging what mistake I had made in the XML window would certainly have been helpful (rather than just the error message).
