### ISSUE TITLE
Potential memory leak on Tomcat

### ISSUE THREAD

**Issue by ryanfb** [sosol/sosol#99]
Getting things like:

```
java.lang.OutOfMemoryError: Java heap space
Exception in thread ""http-bio-8082"-exec-422"  at org.jruby.rack.AbstractFilter.doFilter(AbstractFilter.java:61)
```

And then the server falls over. Have just now bumped to `-Xmx4G` to see if that helps.

Current versions:
- jruby-1.7.12
- java version "1.7.0_85" OpenJDK Runtime Environment (rhel-2.6.1.3.el6_6-x86_64 u85-b01) 
- Apache Tomcat Version 7.0.16

**Comment by balmas** [comment]
FWIW we run the rails 2 version under tomcat with -Xmx12288m -Xms8192m

**Comment by hcayless** [comment]
That doesn’t bode well. I’ll set it up to do a heap dump when it runs out of heap. Analysing JRuby heaps is an exercise in much frustration typically.

**Comment by ryanfb** [comment]
@hcayless Would setting `-Djruby.reify.classes=true` help with that? http://blog.headius.com/2010/07/browsing-memory-jruby-way.html

**Comment by balmas** [comment]
FYI, it seems that there might be an issue when you deploy updated wars to tomcat without restarting the server, possibly limited to the mysql database connections but possibly not. I had been seeing drastically reduced performance after a number of deployments, particularly on acquiring a database connection.  The problem disappeared after a restart of tomcat.  I took a look at the logs for our mySQL instance from that day, and the number of connections had spiked up to over 60, something that shouldn't technically be possible with a connection pool of 20 (and which had previously been set at 5 without an issue). Since then I've been restarting tomcat when I deploy new code and so far that problem hasn't resurfaced.

**Comment by hcayless** [comment]
Yeah, I've seen that too. IIRC, it's a known problem with JRuby deployment
via swapping war files that db connections aren't properly recycled. We
always just restart.

**Comment by ryanfb** [comment]
I noticed some memory leak warnings in the Tomcat log as well: https://gist.github.com/ryanfb/6b0580581c29501ec18b

Not sure if bumping the JRuby version (we're about 10 behind) might address some of those.

**Comment by hcayless** [comment]
We should try that. We were stuck originally because of Grit/POSIX process
handling nastiness, but presumably that's no longer a problem...
